name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.actor }}
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
